from . import help
from . import start
from . import python
from . import max
from . import c
from . import java
from . import python_darslari
from . import python_s
from . import max_darslari
from . import java_darslari
from . import c_darslari
from . import front_e
from . import php
from . import f
from . import ph
from . import c_hash
from . import s_m_m
from . import smm_darslari
from . import c_hash_darslari
from . import androi_d
from . import android_darslari
from . import photoshop
from . import Photoshop_darslari
from . import echo