from . import video_darslar
from . import python_tugma
from . import max
from . import java
from . import ccc
from . import frontend
from . import PHP
from . import smm
from . import c
from . import android
from . import photo_shop